import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Eye, EyeOff, KeyRound, Loader2, Lock, Phone } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { supabase } from "@/integrations/supabase/client";

export default function ResetPassword() {
  const navigate = useNavigate();
  const [phone, setPhone] = useState(""); const [otp, setOtp] = useState(""); const [otpSent, setOtpSent] = useState(false);
  const [password, setPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState("");
  const [showPassword, setShowPassword] = useState(false); const [showConfirmPassword, setShowConfirmPassword] = useState(false); const [loading, setLoading] = useState(false);
  const sendOtp = async () => { if (phone.length < 11) return toast.error("সঠিক মোবাইল নম্বর দিন"); setLoading(true); try { const { data, error } = await supabase.functions.invoke("send-sms-otp", { body: { phone, purpose: "password_reset" } }); if (error || data?.error) throw new Error(data?.error || "OTP পাঠানো যায়নি"); setOtpSent(true); toast.success("এই নম্বরে অ্যাকাউন্ট থাকলে OTP পাঠানো হয়েছে।"); } catch (error) { toast.error(error instanceof Error ? error.message : "OTP পাঠানো যায়নি"); } finally { setLoading(false); } };
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!/^\d{6}$/.test(otp)) return toast.error("৬ সংখ্যার OTP দিন"); if (password.length < 6) return toast.error("পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে"); if (password !== confirmPassword) return toast.error("দুটি পাসওয়ার্ড মিলছে না"); setLoading(true); try { const { data, error } = await supabase.functions.invoke("reset-password-with-phone", { body: { phone, otp, password } }); if (error || data?.error) throw new Error(data?.error || "পাসওয়ার্ড পরিবর্তন করা যায়নি"); toast.success("পাসওয়ার্ড পরিবর্তন হয়েছে। এখন সাইন ইন করুন।"); navigate("/auth", { replace: true }); } catch (error) { toast.error(error instanceof Error ? error.message : "পাসওয়ার্ড পরিবর্তন করা যায়নি"); } finally { setLoading(false); } };
  const PasswordInput = ({ confirm = false }: { confirm?: boolean }) => { const show = confirm ? showConfirmPassword : showPassword; const setShow = confirm ? setShowConfirmPassword : setShowPassword; const value = confirm ? confirmPassword : password; const setValue = confirm ? setConfirmPassword : setPassword; return <div className="relative"><Lock className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" /><Input type={show ? "text" : "password"} placeholder={confirm ? "পাসওয়ার্ড আবার দিন" : "নতুন পাসওয়ার্ড"} value={value} onChange={(e) => setValue(e.target.value)} className="pl-10 pr-10" required minLength={6} /><button type="button" onClick={() => setShow(!show)} className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground" aria-label={show ? "পাসওয়ার্ড লুকান" : "পাসওয়ার্ড দেখুন"}>{show ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}</button></div>; };
  return <div className="min-h-screen flex items-center justify-center bg-background px-4"><Card className="w-full max-w-md"><CardHeader className="text-center"><CardTitle className="text-2xl">পাসওয়ার্ড রিসেট করুন</CardTitle><CardDescription>{otpSent ? "OTP ও নতুন পাসওয়ার্ড দিন" : "মোবাইল নম্বরে OTP পাঠানো হবে"}</CardDescription></CardHeader><CardContent>{!otpSent ? <div className="space-y-4"><div className="relative"><Phone className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" /><Input type="tel" placeholder="01XXXXXXXXX" value={phone} onChange={(e) => setPhone(e.target.value)} className="pl-10" maxLength={14} /></div><Button type="button" className="w-full" onClick={sendOtp} disabled={loading}>{loading ? <Loader2 className="h-4 w-4 animate-spin mr-2" /> : <KeyRound className="h-4 w-4 mr-2" />}OTP পাঠান</Button></div> : <form onSubmit={submit} className="space-y-4"><Input inputMode="numeric" maxLength={6} placeholder="৬ সংখ্যার OTP" value={otp} onChange={(e) => setOtp(e.target.value.replace(/\D/g, ""))} /><PasswordInput /><PasswordInput confirm /><Button type="submit" className="w-full" disabled={loading}>{loading ? <Loader2 className="h-4 w-4 animate-spin mr-2" /> : <KeyRound className="h-4 w-4 mr-2" />}নতুন পাসওয়ার্ড সংরক্ষণ করুন</Button><Button type="button" variant="ghost" className="w-full" onClick={sendOtp} disabled={loading}>OTP আবার পাঠান</Button></form>}<Button type="button" variant="ghost" className="w-full mt-3" onClick={() => navigate("/auth")}>সাইন ইন পেইজে ফিরে যান</Button></CardContent></Card></div>;
}
