
-- Remove old cron jobs
SELECT cron.unschedule('refresh-category-products-daily');
SELECT cron.unschedule('refresh-category-products-daily-2');
SELECT cron.unschedule('refresh-category-products-daily-3');
SELECT cron.unschedule('refresh-category-products-daily-4');

-- Create individual cron jobs for each category (1 per minute starting at 3:00 AM)
SELECT cron.schedule('refresh-cat-shoes', '0 3 * * *', $$select net.http_post(url:='https://kcihftfgmsrpcljsbjdj.supabase.co/functions/v1/refresh-category-products',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjaWhmdGZnbXNycGNsanNiamRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0MTU0OTYsImV4cCI6MjA4Mzk5MTQ5Nn0.CuT0BbMHXNCB4Vh6HDpVKlcRHOZbWV_-H_euAxLY1s0"}'::jsonb,body:='{"categories":["shoes"]}'::jsonb) as request_id;$$);

SELECT cron.schedule('refresh-cat-bag', '1 3 * * *', $$select net.http_post(url:='https://kcihftfgmsrpcljsbjdj.supabase.co/functions/v1/refresh-category-products',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjaWhmdGZnbXNycGNsanNiamRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0MTU0OTYsImV4cCI6MjA4Mzk5MTQ5Nn0.CuT0BbMHXNCB4Vh6HDpVKlcRHOZbWV_-H_euAxLY1s0"}'::jsonb,body:='{"categories":["bag"]}'::jsonb) as request_id;$$);

SELECT cron.schedule('refresh-cat-jewelry', '2 3 * * *', $$select net.http_post(url:='https://kcihftfgmsrpcljsbjdj.supabase.co/functions/v1/refresh-category-products',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjaWhmdGZnbXNycGNsanNiamRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0MTU0OTYsImV4cCI6MjA4Mzk5MTQ5Nn0.CuT0BbMHXNCB4Vh6HDpVKlcRHOZbWV_-H_euAxLY1s0"}'::jsonb,body:='{"categories":["jewelry"]}'::jsonb) as request_id;$$);

SELECT cron.schedule('refresh-cat-beauty', '3 3 * * *', $$select net.http_post(url:='https://kcihftfgmsrpcljsbjdj.supabase.co/functions/v1/refresh-category-products',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjaWhmdGZnbXNycGNsanNiamRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0MTU0OTYsImV4cCI6MjA4Mzk5MTQ5Nn0.CuT0BbMHXNCB4Vh6HDpVKlcRHOZbWV_-H_euAxLY1s0"}'::jsonb,body:='{"categories":["beauty products"]}'::jsonb) as request_id;$$);

SELECT cron.schedule('refresh-cat-men', '4 3 * * *', $$select net.http_post(url:='https://kcihftfgmsrpcljsbjdj.supabase.co/functions/v1/refresh-category-products',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjaWhmdGZnbXNycGNsanNiamRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0MTU0OTYsImV4cCI6MjA4Mzk5MTQ5Nn0.CuT0BbMHXNCB4Vh6HDpVKlcRHOZbWV_-H_euAxLY1s0"}'::jsonb,body:='{"categories":["men clothing"]}'::jsonb) as request_id;$$);

SELECT cron.schedule('refresh-cat-women', '5 3 * * *', $$select net.http_post(url:='https://kcihftfgmsrpcljsbjdj.supabase.co/functions/v1/refresh-category-products',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjaWhmdGZnbXNycGNsanNiamRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0MTU0OTYsImV4cCI6MjA4Mzk5MTQ5Nn0.CuT0BbMHXNCB4Vh6HDpVKlcRHOZbWV_-H_euAxLY1s0"}'::jsonb,body:='{"categories":["women clothing"]}'::jsonb) as request_id;$$);

SELECT cron.schedule('refresh-cat-baby', '6 3 * * *', $$select net.http_post(url:='https://kcihftfgmsrpcljsbjdj.supabase.co/functions/v1/refresh-category-products',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjaWhmdGZnbXNycGNsanNiamRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0MTU0OTYsImV4cCI6MjA4Mzk5MTQ5Nn0.CuT0BbMHXNCB4Vh6HDpVKlcRHOZbWV_-H_euAxLY1s0"}'::jsonb,body:='{"categories":["baby items"]}'::jsonb) as request_id;$$);

SELECT cron.schedule('refresh-cat-eyewear', '7 3 * * *', $$select net.http_post(url:='https://kcihftfgmsrpcljsbjdj.supabase.co/functions/v1/refresh-category-products',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjaWhmdGZnbXNycGNsanNiamRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0MTU0OTYsImV4cCI6MjA4Mzk5MTQ5Nn0.CuT0BbMHXNCB4Vh6HDpVKlcRHOZbWV_-H_euAxLY1s0"}'::jsonb,body:='{"categories":["eyewear sunglasses"]}'::jsonb) as request_id;$$);

SELECT cron.schedule('refresh-cat-office', '8 3 * * *', $$select net.http_post(url:='https://kcihftfgmsrpcljsbjdj.supabase.co/functions/v1/refresh-category-products',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjaWhmdGZnbXNycGNsanNiamRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0MTU0OTYsImV4cCI6MjA4Mzk5MTQ5Nn0.CuT0BbMHXNCB4Vh6HDpVKlcRHOZbWV_-H_euAxLY1s0"}'::jsonb,body:='{"categories":["office supplies"]}'::jsonb) as request_id;$$);

SELECT cron.schedule('refresh-cat-seasonal', '9 3 * * *', $$select net.http_post(url:='https://kcihftfgmsrpcljsbjdj.supabase.co/functions/v1/refresh-category-products',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjaWhmdGZnbXNycGNsanNiamRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0MTU0OTYsImV4cCI6MjA4Mzk5MTQ5Nn0.CuT0BbMHXNCB4Vh6HDpVKlcRHOZbWV_-H_euAxLY1s0"}'::jsonb,body:='{"categories":["seasonal products"]}'::jsonb) as request_id;$$);

SELECT cron.schedule('refresh-cat-phone', '10 3 * * *', $$select net.http_post(url:='https://kcihftfgmsrpcljsbjdj.supabase.co/functions/v1/refresh-category-products',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjaWhmdGZnbXNycGNsanNiamRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0MTU0OTYsImV4cCI6MjA4Mzk5MTQ5Nn0.CuT0BbMHXNCB4Vh6HDpVKlcRHOZbWV_-H_euAxLY1s0"}'::jsonb,body:='{"categories":["phone accessories"]}'::jsonb) as request_id;$$);

SELECT cron.schedule('refresh-cat-sports', '11 3 * * *', $$select net.http_post(url:='https://kcihftfgmsrpcljsbjdj.supabase.co/functions/v1/refresh-category-products',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjaWhmdGZnbXNycGNsanNiamRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0MTU0OTYsImV4cCI6MjA4Mzk5MTQ5Nn0.CuT0BbMHXNCB4Vh6HDpVKlcRHOZbWV_-H_euAxLY1s0"}'::jsonb,body:='{"categories":["sports fitness"]}'::jsonb) as request_id;$$);

SELECT cron.schedule('refresh-cat-entertainment', '12 3 * * *', $$select net.http_post(url:='https://kcihftfgmsrpcljsbjdj.supabase.co/functions/v1/refresh-category-products',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjaWhmdGZnbXNycGNsanNiamRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0MTU0OTYsImV4cCI6MjA4Mzk5MTQ5Nn0.CuT0BbMHXNCB4Vh6HDpVKlcRHOZbWV_-H_euAxLY1s0"}'::jsonb,body:='{"categories":["entertainment"]}'::jsonb) as request_id;$$);

SELECT cron.schedule('refresh-cat-watches', '13 3 * * *', $$select net.http_post(url:='https://kcihftfgmsrpcljsbjdj.supabase.co/functions/v1/refresh-category-products',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjaWhmdGZnbXNycGNsanNiamRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0MTU0OTYsImV4cCI6MjA4Mzk5MTQ5Nn0.CuT0BbMHXNCB4Vh6HDpVKlcRHOZbWV_-H_euAxLY1s0"}'::jsonb,body:='{"categories":["watches"]}'::jsonb) as request_id;$$);

SELECT cron.schedule('refresh-cat-auto', '14 3 * * *', $$select net.http_post(url:='https://kcihftfgmsrpcljsbjdj.supabase.co/functions/v1/refresh-category-products',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjaWhmdGZnbXNycGNsanNiamRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0MTU0OTYsImV4cCI6MjA4Mzk5MTQ5Nn0.CuT0BbMHXNCB4Vh6HDpVKlcRHOZbWV_-H_euAxLY1s0"}'::jsonb,body:='{"categories":["automobile accessories"]}'::jsonb) as request_id;$$);

SELECT cron.schedule('refresh-cat-pet', '15 3 * * *', $$select net.http_post(url:='https://kcihftfgmsrpcljsbjdj.supabase.co/functions/v1/refresh-category-products',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjaWhmdGZnbXNycGNsanNiamRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0MTU0OTYsImV4cCI6MjA4Mzk5MTQ5Nn0.CuT0BbMHXNCB4Vh6HDpVKlcRHOZbWV_-H_euAxLY1s0"}'::jsonb,body:='{"categories":["pet supplies"]}'::jsonb) as request_id;$$);

SELECT cron.schedule('refresh-cat-outdoor', '16 3 * * *', $$select net.http_post(url:='https://kcihftfgmsrpcljsbjdj.supabase.co/functions/v1/refresh-category-products',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjaWhmdGZnbXNycGNsanNiamRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0MTU0OTYsImV4cCI6MjA4Mzk5MTQ5Nn0.CuT0BbMHXNCB4Vh6HDpVKlcRHOZbWV_-H_euAxLY1s0"}'::jsonb,body:='{"categories":["outdoor travelling"]}'::jsonb) as request_id;$$);

SELECT cron.schedule('refresh-cat-electronics', '17 3 * * *', $$select net.http_post(url:='https://kcihftfgmsrpcljsbjdj.supabase.co/functions/v1/refresh-category-products',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjaWhmdGZnbXNycGNsanNiamRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0MTU0OTYsImV4cCI6MjA4Mzk5MTQ5Nn0.CuT0BbMHXNCB4Vh6HDpVKlcRHOZbWV_-H_euAxLY1s0"}'::jsonb,body:='{"categories":["electronics gadgets"]}'::jsonb) as request_id;$$);

SELECT cron.schedule('refresh-cat-kitchen', '18 3 * * *', $$select net.http_post(url:='https://kcihftfgmsrpcljsbjdj.supabase.co/functions/v1/refresh-category-products',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjaWhmdGZnbXNycGNsanNiamRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0MTU0OTYsImV4cCI6MjA4Mzk5MTQ5Nn0.CuT0BbMHXNCB4Vh6HDpVKlcRHOZbWV_-H_euAxLY1s0"}'::jsonb,body:='{"categories":["kitchen gadgets"]}'::jsonb) as request_id;$$);

SELECT cron.schedule('refresh-cat-tools', '19 3 * * *', $$select net.http_post(url:='https://kcihftfgmsrpcljsbjdj.supabase.co/functions/v1/refresh-category-products',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjaWhmdGZnbXNycGNsanNiamRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0MTU0OTYsImV4cCI6MjA4Mzk5MTQ5Nn0.CuT0BbMHXNCB4Vh6HDpVKlcRHOZbWV_-H_euAxLY1s0"}'::jsonb,body:='{"categories":["tools home improvement"]}'::jsonb) as request_id;$$);

SELECT cron.schedule('refresh-cat-school', '20 3 * * *', $$select net.http_post(url:='https://kcihftfgmsrpcljsbjdj.supabase.co/functions/v1/refresh-category-products',headers:='{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjaWhmdGZnbXNycGNsanNiamRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0MTU0OTYsImV4cCI6MjA4Mzk5MTQ5Nn0.CuT0BbMHXNCB4Vh6HDpVKlcRHOZbWV_-H_euAxLY1s0"}'::jsonb,body:='{"categories":["school supplies"]}'::jsonb) as request_id;$$);
